### ISSUE TITLE
Exploratory data analysis (2/2)

### ISSUE THREAD

**Issue by alvarobernal2412** [FID2425/ml-olympiad-earthquake-dmg-24#2]
- [x] Correlation checking to identify most relevant features
- [x] Boolean columns visualization and interpretation
- [x] Final step: Conclusions on data quality and possible data processing
  - [ ] Evaluate data normalization (if applicable)
  - [x] Evaluate columns to be dropped
  - [x] Evaluate possible new columns

**Comment by adrrf** [comment]
Add in correlation comments that correlations are weak or moderate. Also add that no significant correlation is seen between features so no feature deletion is done
